extends Node

signal tick_started(n: int)
signal tick_ended(n: int)
signal simulation_started()
signal simulation_ended(result: Dictionary)
signal agent_action_chosen(id: int, action: String)
signal agent_moved(id: int, from: Vector2i, to: Vector2i)
signal agent_blocked_move(id: int, from: Vector2i, target: Vector2i, reason: String)
signal agent_status_changed(id: int, effect: String, added: bool)
signal agent_captured(id: int)
signal agent_escaped(id: int)
signal agent_eliminated(id: int)
signal agent_eliminated_by_fire(id: int)
signal agent_respawned(id: int)
signal agent_entered_fire(id: int, tile: Vector2i)
signal dog_state_changed(id: int, state: String)
signal dog_spotted_prisoner(agent_id: int, tile: Vector2i)
signal dog_engaged_prisoner(agent_id: int, duration_ticks: int)
signal dog_released_prisoner(agent_id: int)
signal police_captured_while_dog_latched(prisoner_id: int)
signal door_state_changed(tile: Vector2i, state: String)
signal exit_activated(tile: Vector2i)
signal exit_deactivated(tile: Vector2i)
signal minimax_decision(id: int, candidates: Array, chosen: Dictionary)
signal mcts_decision(id: int, root_visits: int, candidates: Array, chosen: Dictionary)
signal fuzzy_decision(id: int, inputs: Dictionary, rule_activations: Array, output: String, chosen_pos: Vector2i)
# FIX #4: fuzzy_debug carries all four defuzzified scores for live HUD bar charts.
signal fuzzy_debug(data: Dictionary)
# MODERATE #2 FIX: separate timeout signal so lockdown never touches capture_count.
signal agent_timed_out(agent_id: int)
signal danger_map_updated()
signal overlay_toggled(overlay_name: String, is_visible: bool)
signal benchmark_run_completed(idx: int, metrics: Dictionary)

# CCTV + telemetry
signal camera_detection(camera_id: int, agent_id: int, visible: bool, tile: Vector2i, detail: Dictionary)
signal camera_sweep_updated(camera_states: Array)
signal cycle_summary_generated(summary: Dictionary)
signal score_event(agent_id: int, delta: float, reason: String, team: String)
