extends Node

signal tick_started(n: int)
signal tick_ended(n: int)
signal simulation_started()
signal simulation_ended(result: Dictionary)
signal agent_action_chosen(id: int, action: String)
signal agent_moved(id: int, from: Vector2i, to: Vector2i)
signal agent_status_changed(id: int, effect: String, added: bool)
signal agent_captured(id: int)
signal agent_escaped(id: int)
signal agent_respawned(id: int)
signal agent_entered_fire(id: int, tile: Vector2i)
signal dog_state_changed(id: int, state: String)
signal door_state_changed(tile: Vector2i, state: String)
signal exit_activated(tile: Vector2i)
signal exit_deactivated(tile: Vector2i)
signal minimax_decision(id: int, candidates: Array, chosen: Dictionary)
signal mcts_decision(id: int, root_visits: int, candidates: Array, chosen: Dictionary)
signal fuzzy_decision(id: int, inputs: Dictionary, rule_activations: Array, output: String, chosen_pos: Vector2i)
signal danger_map_updated()
signal overlay_toggled(overlay_name: String, is_visible: bool)
signal benchmark_run_completed(idx: int, metrics: Dictionary)
